version: '3'
services:
  app:
    restart: always
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
